### ISSUE TITLE
Modification of Obj-GAN

### ISSUE THREAD

**Issue by MarkMoHR** [lzhbrian/arbitrary-text-to-image-papers#2]
hi, @lzhbrian 

I think
`Obj-GAN` should be moved to "***scene graph/layout to image***" section,

since it is based on [Inferring Semantic Layout for Hierarchical Text-to-Image Synthesis](https://arxiv.org/abs/1801.05091).

**Comment by lzhbrian** [comment]
Thanks, I agree with you. Would you like to make a PR for that?
